version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: news_aggregator_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_app
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - news_aggregator_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news_aggregator_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    networks:
      - news_aggregator_network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_app
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      NEWSAPI_KEY: 33543a70b75c4ba88d78144d1dc41de1
      GUARDIAN_KEY: bd7c4feb-b94a-42ce-9cf2-73557ef3f7d0
      NYT_KEY: H7H0hJWJeDKFSh04FKgP8rhfOAIuzbzq
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000

  # Nginx for Backend
  nginx:
    image: nginx:alpine
    container_name: news_aggregator_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news_aggregator_network
    depends_on:
      - backend

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news_aggregator_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - news_aggregator_network
    depends_on:
      - nginx

volumes:
  mysql_data:

networks:
  news_aggregator_network:
    driver: bridge 